global using System;
global using System.Runtime.CompilerServices;
global using System.Threading.Tasks;
global using Divstack.Company.Estimation.Tool.Valuations.Application.Common.Contracts;
global using Ardalis.ApiEndpoints;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Swashbuckle.AspNetCore.Annotations;
