##@url2 = https://localhost:5001/api/users-module/Users

##GET {{url2}}

@url = https://localhost:5001/api/users-module/Authentication

POST {{url}} Content-Type: application/json

{
  "userName": "user_test@ailleron_test.com",
  "password": "3wsx$EDC5rfv"
}





