global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Threading;
global using System.Threading.Tasks;
global using Divstack.Company.Estimation.Tool.Payments.Domain.Payments;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
