@qaUrl = https://estimation-tool-kb.herokuapp.com
@localUrl = http://localhost:5000
@url = http://localhost:5000
@adminEmail = estimationfulladmin-test-2@divstack.pl
@password = 3wsx$EDC5rfvtest4

### Sign In Admin
# @name sign_in_admin
POST {{url}}/api/users-module/Authentication  HTTP/1.1
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{password}}"
}

### Tokens
@token =  {{sign_in_admin.response.body.$.token}}
@bearer = Bearer {{token}}

### inquiry
@inquiry = e140fdb3-6275-40f2-a227-e6a68e2b003c

### service 
@service = b50f98cb-de73-4637-85e6-81477aa7910e

### Made Inquiry
POST {{url}}/api/inquries-module/Inquiries
content-type: application/json

{
  "FirstName": "test",
  "LastName": "test",
  "Email": "kamilbaczek98@gmail.com",
  "PhoneNumber": "+48793751966",
  "AskedServiceDtos": [
    {
      "Id": "{{service}}",
      "Attributes": [
        {
          "AttributeId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "ValueId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        }
      ]
    }
  ]
}

### Get all valuations
GET {{url}}/api/valuations-module/Valuations
content-type: application/json
Authorization: {{bearer}}

### valuation
@valuation = "ec0ae456-f57f-44e2-9e83-308fb1f9c737"

### Suggest proposal
POST {{url}}/api/valuations-module/valuations/proposals
Authorization: {{bearer}}
Content-Type: application/json

{
  "Currency": "USD",
  "Value": 5342,
  "Description": "string",
  "ValuationId": {{valuation}}
}

### Approve proposal
PATCH {{url}}/api/valuations-module/valuations/proposals/approve
Content-Type: application/json

{
  "ProposalId": "fc7ae7cc-5aa0-4ec6-9916-b9385a29db58",
  "ValuationId": {{valuation}}
}

### Complete proposal
PATCH {{url}}/api/valuations-module/valuations/complete
Authorization: {{bearer}}
Content-Type: application/json

{
  "ValuationId": {{valuation}}
}


### Get valuation 
GET {{url}}/api/valuations-module/Valuations/{{valuation}}
content-type: application/json
Authorization: {{bearer}}