@url = http://localhost:5000
@adminEmail = admin@divstack.pl
@password = 3wsx$EDC5rfvtest4

### Sign In Admin
# @name sign_in_admin
POST {{url}}/api/users-module/Authentication  HTTP/1.1
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{password}}"
}

### Tokens
@token =  {{sign_in_admin.response.body.$.token}}
@bearer = Bearer {{token}}

### inquiry
@inquiry = e140fdb3-6275-40f2-a227-e6a68e2b003c

### service 
@service = b50f98cb-de73-4637-85e6-81477aa7910e

### Made Inquiry
POST {{url}}/api/inquries-module/Inquiries
content-type: application/json

{
  "FirstName": "test",
  "LastName": "test",
  "Email": "test@mail.com",
  "AskedServiceDtos": [
    {
      "Id": "{{service}}",
      "Attributes": [
        {
          "AttributeId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "ValueId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        }
      ]
    }
  ]
}

### Get all valuations
GET {{url}}/api/valuations-module/Valuations
content-type: application/json
Authorization: {{bearer}}

### valuation
@valuation = 2f94d822-9ea4-4b5d-a5df-5c55f3b3e968

### Suggest proposal
POST {{url}}/api/valuations-module/Valuations/valuations/proposals
content-type: application/json
Authorization: {{bearer}}
Content-Type: application/json

{
  "Currency": "USD",
  "Value": 42,
  "Description": "string",
  "ValuationId": {{valuation}}
}

### Get all valuation history
GET {{url}}/api/valuations-module/Valuations/valuations/history/{{valuation}}
content-type: application/json
Authorization: {{bearer}}

### Get valuation 
GET {{url}}/api/valuations-module/Valuations/{{valuation}}
content-type: application/json
Authorization: {{bearer}}