version: '3.9'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 127.0.0.1 --blobPort 10010 --queueHost 127.0.0.1 --queuePort 10011"
    ports:
      - "10010:10010"
      - "10011:10011"
  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"