// <auto-generated />
using System;
using Divstack.Company.Estimation.Tool.Estimations.Persistance.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Divstack.Company.Estimation.Tool.Estimations.Persistance.Migrations
{
    [DbContext(typeof(ValuationsContext))]
    [Migration("20210624065035_Init_valuations_module")]
    partial class Init_valuations_module
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Valuation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("varbinary(16)");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Valuations");
                });

            modelBuilder.Entity("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Valuation", b =>
                {
                    b.OwnsOne("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Equeries.Enquiry", "Enquiry", b1 =>
                        {
                            b1.Property<byte[]>("ValuationId")
                                .HasColumnType("varbinary(16)");

                            b1.HasKey("ValuationId");

                            b1.ToTable("Valuations");

                            b1.WithOwner()
                                .HasForeignKey("ValuationId");

                            b1.OwnsOne("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Client", "Client", b2 =>
                                {
                                    b2.Property<byte[]>("EnquiryValuationId")
                                        .HasColumnType("varbinary(16)");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("EnquiryValuationId");

                                    b2.ToTable("Valuations");

                                    b2.WithOwner()
                                        .HasForeignKey("EnquiryValuationId");

                                    b2.OwnsOne("Divstack.Company.Estimation.Tool.Shared.DDD.ValueObjects.Emails.Email", "Email", b3 =>
                                        {
                                            b3.Property<byte[]>("ClientEnquiryValuationId")
                                                .HasColumnType("varbinary(16)");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("varchar(255)");

                                            b3.HasKey("ClientEnquiryValuationId");

                                            b3.ToTable("Valuations");

                                            b3.WithOwner()
                                                .HasForeignKey("ClientEnquiryValuationId");
                                        });

                                    b2.Navigation("Email");
                                });

                            b1.OwnsMany("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Equeries.InquiryService", "InquiryServices", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("varbinary(16)");

                                    b2.Property<byte[]>("EnquiryValuationId")
                                        .IsRequired()
                                        .HasColumnType("varbinary(16)");

                                    b2.Property<Guid?>("ServiceId")
                                        .HasColumnType("varbinary(16)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("EnquiryValuationId");

                                    b2.ToTable("InquiryServices");

                                    b2.WithOwner("Enquiry")
                                        .HasForeignKey("EnquiryValuationId");

                                    b2.Navigation("Enquiry");
                                });

                            b1.Navigation("Client");

                            b1.Navigation("InquiryServices");
                        });

                    b.OwnsMany("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.History.HistoricalEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("varbinary(16)");

                            b1.Property<DateTime>("ChangeDate")
                                .HasColumnType("datetime");

                            b1.Property<byte[]>("ValuationId")
                                .IsRequired()
                                .HasColumnType("varbinary(16)");

                            b1.HasKey("Id");

                            b1.HasIndex("ValuationId");

                            b1.ToTable("History");

                            b1.WithOwner("Valuation")
                                .HasForeignKey("ValuationId");

                            b1.OwnsOne("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.ValuationStatus", "Status", b2 =>
                                {
                                    b2.Property<byte[]>("HistoricalEntryId")
                                        .HasColumnType("varbinary(16)");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HistoricalEntryId");

                                    b2.ToTable("History");

                                    b2.WithOwner()
                                        .HasForeignKey("HistoricalEntryId");
                                });

                            b1.Navigation("Status");

                            b1.Navigation("Valuation");
                        });

                    b.OwnsMany("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Proposals.Proposal", "Proposals", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("varbinary(16)");

                            b1.Property<DateTime?>("Cancelled")
                                .HasColumnType("datetime");

                            b1.Property<Guid?>("CancelledBy")
                                .HasColumnType("varbinary(16)");

                            b1.Property<DateTime>("Suggested")
                                .HasColumnType("datetime");

                            b1.Property<Guid>("SuggestedBy")
                                .HasColumnType("varbinary(16)");

                            b1.Property<byte[]>("ValuationId")
                                .IsRequired()
                                .HasColumnType("varbinary(16)");

                            b1.HasKey("Id");

                            b1.HasIndex("ValuationId");

                            b1.ToTable("Proposals");

                            b1.WithOwner("Valuation")
                                .HasForeignKey("ValuationId");

                            b1.OwnsOne("Divstack.Company.Estimation.Tool.Shared.DDD.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<byte[]>("ProposalId")
                                        .HasColumnType("varbinary(16)");

                                    b2.Property<string>("Currency")
                                        .HasColumnType("text");

                                    b2.Property<decimal?>("Value")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("decimal(18, 2)");

                                    b2.HasKey("ProposalId");

                                    b2.ToTable("Proposals");

                                    b2.WithOwner()
                                        .HasForeignKey("ProposalId");
                                });

                            b1.OwnsOne("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Proposals.ProposalDecision", "Decision", b2 =>
                                {
                                    b2.Property<byte[]>("ProposalId")
                                        .HasColumnType("varbinary(16)");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("varchar(10)");

                                    b2.Property<DateTime?>("Date")
                                        .IsRequired()
                                        .HasColumnType("datetime");

                                    b2.HasKey("ProposalId");

                                    b2.ToTable("Proposals");

                                    b2.WithOwner()
                                        .HasForeignKey("ProposalId");
                                });

                            b1.OwnsOne("Divstack.Company.Estimation.Tool.Valuations.Domain.Valuations.Proposals.ProposalDescription", "Description", b2 =>
                                {
                                    b2.Property<byte[]>("ProposalId")
                                        .HasColumnType("varbinary(16)");

                                    b2.Property<string>("Message")
                                        .HasMaxLength(512)
                                        .HasColumnType("varchar(512)");

                                    b2.HasKey("ProposalId");

                                    b2.ToTable("Proposals");

                                    b2.WithOwner()
                                        .HasForeignKey("ProposalId");
                                });

                            b1.Navigation("Decision");

                            b1.Navigation("Description");

                            b1.Navigation("Price");

                            b1.Navigation("Valuation");
                        });

                    b.Navigation("Enquiry");

                    b.Navigation("History");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
