// <auto-generated />
using System;
using Divstack.Company.Estimation.Tool.Products.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Divstack.Company.Estimation.Tool.Products.DAL.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20210327152718_Add_Products_Attributes_And_Possible_Values_For_That_Attributtes")]
    partial class Add_Products_Attributes_And_Possible_Values_For_That_Attributtes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Divstack.Company.Estimation.Tool.Products.Core.Products.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "Products");
                });

            modelBuilder.Entity("Divstack.Company.Estimation.Tool.Products.Core.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "Products");
                });

            modelBuilder.Entity("Divstack.Company.Estimation.Tool.Products.Core.Products.Product", b =>
                {
                    b.HasOne("Divstack.Company.Estimation.Tool.Products.Core.Products.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.OwnsMany("Divstack.Company.Estimation.Tool.Products.Core.Products.Attributes.Attribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("AttributePossibleValues", "Products");

                            b1.WithOwner("Product")
                                .HasForeignKey("ProductId");

                            b1.OwnsMany("Divstack.Company.Estimation.Tool.Products.Core.Products.Attributes.PossibleValues.PossibleValue", "PossibleValues", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("AttributeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("nvarchar(255)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("AttributeId");

                                    b2.ToTable("PossibleValue");

                                    b2.WithOwner("Attribute")
                                        .HasForeignKey("AttributeId");

                                    b2.Navigation("Attribute");
                                });

                            b1.Navigation("PossibleValues");

                            b1.Navigation("Product");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
