@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Web/AzureWebApp.puml

!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Management/AppConfiguration.puml
!includeurl AzurePuml/Integration/AzureServiceBus.puml
!includeurl AzurePuml/Databases/AzureDatabaseForMySQL.puml
!includeurl AzurePuml/Databases/AzureDatabaseForPostgreSQL.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml

LAYOUT_WITH_LEGEND()

title Container diagram for Estimation Tool

Person(estimator, Estimator , "A person who is resposible for suggest valuation proposal on time, based on priorities" )
Person(customer, Customer , "A person who inquiry service" )

AzureWebApp(spa, "Single-Page App", "Angular, JS")

AzureWebApp(webApp, "WebAPI", ".NET 6", "")
Rel_Neighbor(spa, webApp, "Uses", "JSON, HTTPS")
Rel_Back_Neighbor(spa, webApp, "Delivers")

Rel(customer, spa, "Uses", "HTTPS")
Rel(estimator, spa, "Uses", "HTTPS")

AzureApplicationInsights(azureApplicationInsights, "Observability System", "AzureApplicationInsights")
Rel_U(webApp, azureApplicationInsights, "Log request", "")

AzureServiceBus(serviceBus, "Message Broker", "Azure Service Bus", "")
Rel_U(webApp, serviceBus, "Publish", "")
Rel_Back(webApp, serviceBus, "Subscribe", "")

AzureKeyVault(keyVault, "Secrets Store", "Azure Key Valut", "")
AppConfiguration(azureAppConfiguration, "Configuration Management", "Azure App Configuratio", "Contains all configuration entries and feature flags")
Rel_Neighbor(webApp, azureAppConfiguration, "Get configuration")
Rel_Neighbor(azureAppConfiguration, keyVault, "Get secrets")
Rel_Back_Neighbor(azureAppConfiguration, keyVault, "Returns secrets")
Rel_Back_Neighbor(webApp, azureAppConfiguration, "Returns configuration")

AzureCosmosDb(mongoDb, "Document Database", "MongoDB")
AzureDatabaseForMySQL(mySQL, "Relational Database", "MySQL")
AzureDatabaseForPostgreSQL(postgres, "Relational Database", "Postgres")

Rel_D(webApp, mongoDb, "Write")
Rel_Back(webApp, mongoDb, "Read")

Rel_D(webApp, mySQL, "Write")
Rel_Back(webApp, mySQL, "Read")

Rel_D(webApp, postgres, "Write")
Rel_Back(webApp, postgres, "Read")


@enduml