@startuml
!include <c4/C4_Context.puml>  

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

'LAYOUT_WITH_LEGEND

title System Context diagram for Estimation Tool

Person(estimator, Estimator , "<$user> <$mobile_user>\n A person who is resposible for suggest valuation proposal on time, based on priorities" )
Person(customer, Customer , "<$user> <$mobile_user>\n A person who inquiry service" )

System(estimation_tool, "Estimation Tool", "Allows customers to inqury service, approve/reject vaulations, pay after service valuation.")

System_Ext(twillo, "Twillo", "SMS service resposible for send to customers and estimators")
System_Ext(sendGrid, "Send Grid", "Email service resposible for send to customers and estimators")
System_Ext(trello, "Trello", "Email service resposible for send to customers and estimators")
System_Ext(stripe, "Stripe", "Payment Gateway")

Rel(customer, estimation_tool, "Uses")
Rel(estimator, estimation_tool, "Uses")

Rel_U(estimation_tool, twillo, "Sends SMS", "SMS")
Rel_L(estimation_tool, sendGrid, "Sends e-mails", "SMTP")
Rel_L(estimation_tool, trello, "Sends create task", "HTTP")
Rel_Neighbor(estimation_tool, stripe, "Make a payments", "HTTP")

@enduml